[package]
name = "exocore-platform"
version = "0.1.0"
description = "A public orientation shell for Exocore Platform."
authors = ["Hearth & Code"]
license = "MIT"
repository = "https://github.com/hearthandcode/exocore-platform"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "exocore_platform_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
tauri = { version = "2.11.2", features = [] }
