// Generated by scripts/generate_agent_runtime_types.py. Do not edit.
pub const AGENT_RUNTIME_SOURCE_ID: &str = "hub-exocore-agent-runtime-v1";
pub const AGENT_RUNTIME_SOURCE_DIGEST: &str =
    "7666dd8a71589f9fc404f89619675c541b3c59a2c1753eada2ed3912c6ebe59b";
pub const AGENT_RUNTIME_AUTHORITY: &str = "non-authoritative-projection";

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum AgentRuntimeModuleId {
    PolicyRuntime,
    RunLedger,
    ProviderRegistry,
    ToolRuntime,
    MemoryRuntime,
    ContextAssembly,
    AgentRuntime,
    Orchestration,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum ContextLayer {
    KernelPolicy,
    OperatorIdentity,
    HubOperationalGovernance,
    ProgramArchetype,
    RepositoryProject,
    DirectoryLocal,
    TaskWorkflow,
    TurnRuntimeInjection,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum ContextSourceType {
    OperationalCharter,
    AgentsGuide,
    Archetype,
    HubIntelligence,
    SkillMethodology,
    TaskWorkflow,
    MemoryRetrieval,
    RuntimeInjection,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum ContextCacheBand {
    Stable,
    Session,
    Turn,
    Ephemeral,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum LifecycleScope {
    Session,
    Run,
    Turn,
    ContextDiscovery,
    ContextAssembly,
    ModelSelection,
    ProviderRequest,
    ResponseStream,
    Message,
    ToolCall,
    ToolExecution,
    ChildAgent,
    Aggregation,
    Memory,
    Checkpoint,
    Settlement,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum LifecyclePhase {
    Requested,
    Started,
    Updated,
    Completed,
    Failed,
    Cancelled,
    Blocked,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum ActiveRunState {
    Accepted,
    Orienting,
    AssemblingContext,
    SelectingModel,
    InvokingModel,
    AwaitingEffects,
    ProcessingResults,
    Settling,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum TerminalRunState {
    Completed,
    Failed,
    Cancelled,
    Suspended,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum HookPoint {
    Before,
    After,
    Error,
    Finally,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum HookOutcome {
    Continue,
    Append,
    Patch,
    Block,
    Retry,
    Redirect,
    Suspend,
    Terminate,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum OrchestrationStrategy {
    Sequential,
    Parallel,
    Map,
    Reduce,
    Supervisor,
    Debate,
    Handoff,
    Quorum,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum ProviderCapability {
    Streaming,
    Tools,
    StrictTools,
    StructuredOutput,
    Reasoning,
    PromptCaching,
    Files,
    Images,
    Audio,
    Video,
    Embeddings,
    Batch,
    DeferredBackground,
    HostedSearch,
    HostedCodeExecution,
    StatefulContinuation,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum ProviderAuthMode {
    ApiKey,
    OauthPkce,
    OauthDevice,
    SubscriptionKey,
    InteractiveSubscriptionSession,
    WorkloadIdentity,
    RoutedCredential,
    LocalNone,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum ProviderCandidate {
    AnthropicApi,
    ClaudeSubscription,
    OpenaiApi,
    CodexSubscription,
    Openrouter,
    MinimaxApi,
    MinimaxTokenPlan,
    MoonshotKimiApi,
    KimiCodeSubscription,
    Deepseek,
    Xai,
    Gemini,
    HuggingfaceInference,
    Ollama,
    NvidiaNim,
    Mistral,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum ModelEventCategory {
    Lifecycle,
    Content,
    Reasoning,
    Tool,
    Citation,
    Usage,
    Diagnostic,
    Terminal,
}

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,
)]
#[serde(rename_all = "kebab-case")]
pub enum MemoryLifecycle {
    Candidate,
    Admitted,
    Corrected,
    Superseded,
    Expired,
    Revoked,
    Tombstoned,
    Projected,
}
