// Generated by scripts/generate_contract_types.py. Do not edit.
pub const EXOCORE_VOCABULARY_VERSION: &str = "1.0.0";

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum AuthorityClass {
    Source,
    Evidence,
    Inference,
    Hypothesis,
    Proposal,
    Plan,
    Projection,
    Receipt,
    Historical,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Lifecycle {
    Draft,
    Active,
    Deprecated,
    Archived,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ModuleStatus {
    Experimental,
    Active,
    Deprecated,
    Archived,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum OperationKind {
    Command,
    Query,
    Event,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PersistenceRole {
    LocalTransitory,
    DurableAuthority,
    VectorProjection,
    GraphProjection,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum RecordKind {
    Artifact,
    Decision,
    Evidence,
    ModuleState,
    WorkflowRun,
    Receipt,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum RelationKind {
    Contains,
    DependsOn,
    DerivesFrom,
    Supersedes,
    ProjectsTo,
    CorrelatedWith,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum Sensitivity {
    PublicSafe,
    Internal,
    Restricted,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum WorkflowStatus {
    Pending,
    Running,
    Completed,
    Failed,
    Cancelled,
}
