#!/usr/bin/env python3
"""Generate language/taxonomy types from canonical JSON contracts."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VOCABULARY = json.loads((ROOT / "contracts/language/exocore.vocabulary.v1.json").read_text())
TAXONOMY = json.loads((ROOT / "contracts/language/exocore.taxonomy.v1.json").read_text())


def pascal(value: str) -> str:
    return "".join(part.capitalize() for part in value.replace("_", "-").split("-"))


def rust_variant(value: str) -> str:
    return pascal(value)


def render_ts() -> str:
    lines = [
        "// Generated by scripts/generate_contract_types.py. Do not edit.",
        f'export const EXOCORE_VOCABULARY_VERSION = "{VOCABULARY["version"]}" as const;',
        "",
    ]
    terms = [term["id"] for term in VOCABULARY["terms"]]
    lines.append("export const exocoreTerms = [")
    lines.extend(f'  "{term}",' for term in terms)
    lines.extend(["] as const;", "export type ExocoreTerm = (typeof exocoreTerms)[number];", ""])
    for name, values in TAXONOMY["dimensions"].items():
        const_name = name.upper() + "_VALUES"
        type_name = pascal(name)
        lines.append(f"export const {const_name} = [")
        lines.extend(f'  "{value}",' for value in values)
        lines.extend([f"] as const;", f"export type {type_name} = (typeof {const_name})[number];", ""])
    return "\n".join(lines).rstrip() + "\n"


def render_rust() -> str:
    lines = [
        "// Generated by scripts/generate_contract_types.py. Do not edit.",
        f'pub const EXOCORE_VOCABULARY_VERSION: &str = "{VOCABULARY["version"]}";',
        "",
    ]
    for name, values in TAXONOMY["dimensions"].items():
        type_name = pascal(name)
        lines.extend([
            "#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]",
            '#[serde(rename_all = "kebab-case")]' if all("_" not in value for value in values) else '#[serde(rename_all = "snake_case")]',
            f"pub enum {type_name} {{",
        ])
        lines.extend(f"    {rust_variant(value)}," for value in values)
        lines.extend(["}", ""])
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    ts_path = ROOT / "src/contracts/generated/exocore-language.ts"
    rust_path = ROOT / "src-tauri/src/contracts/generated.rs"
    expected = {ts_path: render_ts(), rust_path: render_rust()}
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, body in expected.items() if not path.exists() or path.read_text() != body]
        if stale:
            raise SystemExit("generated contract types are stale: " + ", ".join(stale))
        print("generated contract types are current: 2/2")
        return
    for path, body in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
    print(f"generated {ts_path.relative_to(ROOT)} and {rust_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
