#!/usr/bin/env python3
"""Generate public agent-runtime Rust and TypeScript enums from the projected contract."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts/agent-runtime/exocore.agent-runtime.v1.json"
TS_TARGET = ROOT / "src/contracts/generated/exocore-agent-runtime.ts"
RUST_TARGET = ROOT / "src-tauri/src/contracts/agent_runtime_generated.rs"


def load_source() -> dict[str, Any]:
    try:
        value = json.loads(SOURCE.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot load projected agent-runtime contract: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError("projected agent-runtime contract must be an object")
    return value


def pascal(value: str) -> str:
    return "".join(part.capitalize() for part in re.split(r"[-_]", value))


def ts_block(name: str, values: list[str]) -> list[str]:
    constant = re.sub(r"(?<!^)(?=[A-Z])", "_", name).upper() + "_VALUES"
    return [
        f"export const {constant} = [",
        *(f'  "{value}",' for value in values),
        "] as const;",
        f"export type {name} = (typeof {constant})[number];",
        "",
    ]


def rust_block(name: str, values: list[str]) -> list[str]:
    return [
        "#[derive(",
        "    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize,",
        ")]",
        '#[serde(rename_all = "kebab-case")]',
        f"pub enum {name} {{",
        *(f"    {pascal(value)}," for value in values),
        "}",
        "",
    ]


def groups(source: dict[str, Any]) -> list[tuple[str, list[str]]]:
    return [
        ("AgentRuntimeModuleId", [module["id"] for module in source["modules"]]),
        ("ContextLayer", source["context"]["layers"]),
        ("ContextSourceType", source["context"]["source_types"]),
        ("ContextCacheBand", source["context"]["cache_bands"]),
        ("LifecycleScope", source["lifecycle"]["scopes"]),
        ("LifecyclePhase", source["lifecycle"]["phases"]),
        ("ActiveRunState", source["lifecycle"]["active_run_states"]),
        ("TerminalRunState", source["lifecycle"]["terminal_run_states"]),
        ("HookPoint", source["hooks"]["points"]),
        ("HookOutcome", source["hooks"]["outcomes"]),
        ("OrchestrationStrategy", source["orchestration"]["strategies"]),
        ("ProviderCapability", source["providers"]["capabilities"]),
        ("ProviderAuthMode", source["providers"]["auth_modes"]),
        ("ProviderCandidate", source["providers"]["candidate_modules"]),
        ("ModelEventCategory", source["providers"]["event_categories"]),
        ("MemoryLifecycle", source["memory"]["lifecycle"]),
    ]


def render_ts(source: dict[str, Any]) -> str:
    projection = source["source_projection"]
    lines = [
        "// Generated by scripts/generate_agent_runtime_types.py. Do not edit.",
        f'export const AGENT_RUNTIME_SOURCE_ID = "{projection["source_id"]}" as const;',
        f'export const AGENT_RUNTIME_SOURCE_DIGEST = "{projection["source_package_digest"]}" as const;',
        'export const AGENT_RUNTIME_AUTHORITY = "non-authoritative-projection" as const;',
        "",
    ]
    for name, values in groups(source):
        lines.extend(ts_block(name, values))
    return "\n".join(lines).rstrip() + "\n"


def render_rust(source: dict[str, Any]) -> str:
    projection = source["source_projection"]
    lines = [
        "// Generated by scripts/generate_agent_runtime_types.py. Do not edit.",
        f'pub const AGENT_RUNTIME_SOURCE_ID: &str = "{projection["source_id"]}";',
        "pub const AGENT_RUNTIME_SOURCE_DIGEST: &str =",
        f'    "{projection["source_package_digest"]}";',
        'pub const AGENT_RUNTIME_AUTHORITY: &str = "non-authoritative-projection";',
        "",
    ]
    for name, values in groups(source):
        lines.extend(rust_block(name, values))
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = load_source()
    expected = {TS_TARGET: render_ts(source), RUST_TARGET: render_rust(source)}
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, body in expected.items() if not path.exists() or path.read_text() != body]
        if stale:
            raise SystemExit("generated agent-runtime types are stale: " + ", ".join(stale))
        print("generated agent-runtime types are current: 2/2")
        return
    for path, body in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)
    print("generated agent-runtime Rust and TypeScript types: 2/2")


if __name__ == "__main__":
    main()
